from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
import os


# =========================
# Phase 1 immutable defaults
# =========================

# NOTE: Requirement: QR codes MUST encode the absolute URL:
# https://stellarregistrycommittee.pages.dev/r/<ID>
PUBLIC_BASE_URL = "https://stellarregistrycommittee.pages.dev"

QR_SHORT_PREFIX = "/r/"
REGISTRY_CANONICAL_PREFIX = "/registry/"

DEFAULT_TEMPLATE_ID = "tsrc-letter-v1"

# Build output directory for Cloudflare Pages
PUBLIC_DIRNAME = "public"

# Where entry JSON lives (generated by your registrar tool)
ENTRIES_REL = Path("data") / "entries"

# Where PDF output must be written
CERTIFICATES_REL = Path("certificates")

# Template bundles (immutable directories, versioned by folder name)
TEMPLATES_REL = Path("tools") / "tsrc" / "certificates" / "templates"


@dataclass(frozen=True)
class RepoPaths:
    repo_root: Path
    public_dir: Path
    entries_dir: Path
    certificates_dir: Path
    templates_dir: Path


def get_repo_root() -> Path:
    """
    Resolve repo root.

    Default behavior:
    - assumes this file is at: <repo>/tools/tsrc/config.py
    - repo_root becomes parents[2] (tsrc -> tools -> repo)

    You can override by setting env var TSRC_REPO_ROOT.
    """
    override = os.environ.get("TSRC_REPO_ROOT", "").strip()
    if override:
        return Path(override).expanduser().resolve()

    return Path(__file__).resolve().parents[2]


def get_paths() -> RepoPaths:
    repo_root = get_repo_root()
    public_dir = (repo_root / PUBLIC_DIRNAME).resolve()
    entries_dir = (public_dir / ENTRIES_REL).resolve()
    certificates_dir = (public_dir / CERTIFICATES_REL).resolve()
    templates_dir = (repo_root / TEMPLATES_REL).resolve()

    return RepoPaths(
        repo_root=repo_root,
        public_dir=public_dir,
        entries_dir=entries_dir,
        certificates_dir=certificates_dir,
        templates_dir=templates_dir,
    )


def expected_qr_url(entry_id: str) -> str:
    # Must be absolute, QR-safe, stable.
    return f"{PUBLIC_BASE_URL}{QR_SHORT_PREFIX}{entry_id}"
